#######
title: Farhood Farahnak
# email:
description: PhD student, CLaC Lab, Concordia University
# url: https://encs.concordia.ca/~f_farahn # the base hostname & protocol for your site
# keywords: []

#######

theme: jekyll-theme-tactile

# timezone:          America/New_York
markdown:          kramdown
highlighter:       rouge
excerpt_separator: <!--more-->
permalink:         /articles/:year-:month/:title

kramdown:
  auto_ids: true
  footnote_nr: 1
  entity_output: as_char
  toc_levels: 1..6
enable_coderay: false


#################

owner:
  name: Farhood FF
  avatar: #username
  job: "PhD Student"
  bio: "CLaC Lab"
  email: #username
  #disqus-shortname: renyuanzblog
  twitter: #username
  facebook: #username
  google:
    plus: #username
    analytics: 
    verify:
    ad-client:
    ad-slot:
    site-verification: 
  bing-verify:
  github: #username
  stackoverflow: #username
  linkedin: #username
  xing: #username
  medium: sbetamc
  instagram: #username
  lastfm: #username
  tumblr: #username
  pinterest: #username
  foursquare: #username
  steam: #username
  dribbble: #username
  youtube: #username
  soundcloud: #username
  weibo: #username
  flickr: #username
  codepen: #username
  telegram: #username
  blog: #username
# googlescholar: K9xYnSQAAAAJ
